version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - LD_LIBRARY_PATH=/opt/oracle/instantclient_11_2
    volumes:
      - .:/app
    command: ["python", "app.py"]

