email_settings:
  to_address:
    NTUH01:
      - "Likewhite1119@gmail.com"
      - "shkuo101@ntu.edu.tw"
    VGHTPE02:
      - "b@example.com"
      - "b2@example.com"
    CGMH03:
      - "173623@cch.org.tw"
    KFSYSCC04:
      - "d@example.com"
    MMH05:
      - "abc@panmed.tw"
    CCH07:
      - "f@example.com"
    NCKU08:
      - "abc@panmed.tw"
    OSAKA09:
      - "abc@panmed.tw"
    SAGARA10:
      - "abc@panmed.tw"
    POHAI11:
      - "abc@panmed.tw"
    TMUH12:
      - "abc@panmed.tw"
    VGHTC13:
      - "abc@panmed.tw"
    TZUCHI14:
      - "abc@panmed.tw"
  cc_address: "ywu@panmed.tw"
  subject: "[CSIS Randomization] DCIS_step2_Random {mrn}"
  body_template: |
    Randomized Treatment Allocation:

    Series No. of Allocation: {count}
    Patient Study ID: {mrn}
    Hospital: {hospitalDesc}
    Randomized Treatment Arm: {treatment}
    Stratum:
    {dcis_display}
    {pathology_display}

    Expected number of patients: 5000
    Up-to-date Results in Randomization:
    {treatment_counts}

    Cumulative number of patients allocated to the specific treatment arm in each stratum after this randomization:
    {progress}

